### PR TITLE
Added player dressing from customized data

### PR DESCRIPTION
**Pull request by ShadowBrian**
Some very small code changes to game.cs and player.cs.
I also have a hacky loop in there for removing anything that isn't the head of the worm so we don't get weird looking suits showing up.
Also includes skin color.

Known issue: The hair/hat gets hidden, I think it's because the player camera is marked as first person for some reason, maybe change that in the camera code somewhere?

### CODE REVIEW

**Comment by ShadowBrian** [comment]
Not sure why the checks failed as the code I added was super basic, what kinda weird shit are you running on the pull requests lmao.
Hat hiding fix is to not set the viewer on the camera script, seems to not affect any functionality.

**Comment by ShadowBrian** [comment]
Yeah I dunno wtf I'm supposed to change about my code to have it not freak out.

**Comment by ShadowBrian** [comment]
Seems to be failing on stuff I didn't even touch so that shit's crazy.

**Comment by xezno** [comment]
It's just done for spacing / indentation, there's a couple of places where it needs fixing (visual studio will handle this for you with "Format Document")

**Comment by ShadowBrian** [comment]
"format document" worked.
Seems a little excessive to me but w/e I'm not a programmer on this :p

**Comment by Matt9440** [comment]
Implemented in #38

**Pull request closed without merging**
